"use strict"

const headJobs = [
    '--hap',
    '--mnr',
    'miner', 'quarrier', 'netherminer',
    '--mnr',
    '--crp',
    'lumberjack', 'fletcher', 'sawmill',
    '--crp',
    '--stn',
    'crusher', 'sifter', 'stonemason',
    '--stn',
    '--thr',
    'teacher', 'pupil', 'student', 'combattraining', 'archertraining',
    '--thr',
    '--hlr',
    'healer',
    '--hlr',
    '--frm',
    'farmer', 'planter', 'cowboy', 'shepherd', 'swineherder', 'rabbitherder', 'chickenherder', 'beekeeper', 'florist', 'composter',
    '--frm',
    'baker', 'cook', 'cookassistant',
    '--frm',
    '--fhr',
    'fisherman',
    '--fhr',
    '--smt',
    'smelter', 'blacksmith',
    '--smt',
    '--sts',
    'concretemixer', 'stonesmeltery', 'glassblower', 'dyer',
    '--sts',
    '--bld',
    'builder', 'mechanic',
    '--bld',
    '--alh',
    'alchemist', 'enchanter', 'researcher',
    '--alh',
    '--dlv',
    'deliveryman', 'undertaker',
    '--dlv',
    '--var',
    'knight', 'ranger', 'druid',
    '--var',
]

module.exports = headJobs